name: Deploy to AWS ECS

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Login to AWS ECR
      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      # Step 4: Build the Docker image and push to AWS ECR
      - name: Build and Push Docker Image
        run: |
          docker build -t llm-api .
          docker tag llm-api:latest ${{ secrets.AWS_ECR_URI }}:latest
          docker push ${{ secrets.AWS_ECR_URI }}:latest
          
      # Step 5: Deploy to AWS ECS (Optional)
      - name: Deploy to AWS ECS
        run: |
          # Your ECS deployment steps here (e.g., update ECS service with the new image)
